dist: trusty
sudo: required
language: bash
services:
- docker
notifications:
  email: false
before_install: "./.travis/test-setup.sh"
script: "./.travis/test.sh"
before_deploy: "./.travis/deploy-setup.sh"
deploy:
- skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh staging"
  on:
    branch: develop
git:
  depth: 5
env:
  global:
  - secure: ADmhKnkSyCrheJ0Vpa5X/JribTsux/07i4FbhxBTIq/YM+kkcygkO807UDPcbe8vfYWWxp4lcDTdPTYKvGbyJZIsD6yV17+V10Lp58YjexpKFVzqsqLXG7IFaTCvPvG+vqzu63QI6DNY06Z+aUjeRRXJMIG0pMpCIflzN4bkAcA=
