dist: trusty
sudo: required
language: bash
services:
- docker
notifications:
  email: false
before_install: "./.travis/test-setup.sh"
script: "./.travis/test.sh"
before_deploy: "./.travis/deploy-setup.sh"
deploy:
- skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh staging"
  on:
    branch: develop
git:
  depth: 5
env:
  global:
  - secure: ADmhKnkSyCrheJ0Vpa5X/JribTsux/07i4FbhxBTIq/YM+kkcygkO807UDPcbe8vfYWWxp4lcDTdPTYKvGbyJZIsD6yV17+V10Lp58YjexpKFVzqsqLXG7IFaTCvPvG+vqzu63QI6DNY06Z+aUjeRRXJMIG0pMpCIflzN4bkAcA=
  - secure: eubvvOD8TapXLzjzcDe0MBgE+IGOMDLZPAUwfPc6+H5N8efZoa6nLMhm/7wVYBPpuBQAQC3T3I8YPYh/qJMU8pQ7771FOxqMUXmpvEGUHZoZQ66/Nu0uylBeKwYDc5o7u1Qj1xW+JwCMWpfcUlbCHYPgR5Av/1m62ZFPaCKoj34=
  - secure: E6zBunUrmP6w9RzCSgIY0hS99v8u1L55AGsY1MtPr+u6uMLIkif6uMG/O881DmOkDtBgv/m60fx2Ka+bEZpxWY30ahTc08SUhjMEGC9MeRr5PvEeEzbsiOez+OFIRdngMGptHbTagqKGl3KrJPp21YsYL5GGFWil7iUZ/poent8=
