FROM node:8.6.0

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
WORKDIR /app
RUN npm install
COPY tsconfig.json /app/tsconfig.json
COPY typings/ /app/typings/
COPY source/ /app/source/
RUN npx tsc

ENTRYPOINT [ "node_modules/mocha/bin/_mocha", "output/tests-integration/**/*.js", "--no-timeouts", "--require", "source-map-support/register" ]
