FROM node:8.6.0

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
WORKDIR /app
RUN npm install
COPY tsconfig.json /app/tsconfig.json
COPY typings/ /app/typings/
COPY source/contracts/ /app/source/contracts/
COPY source/deployment/compileContracts.ts /app/source/deployment/compileContracts.ts
COPY source/libraries/Configuration.ts /app/source/libraries/Configuration.ts
COPY source/libraries/ContractCompiler.ts /app/source/libraries/ContractCompiler.ts
RUN npx tsc
RUN node ./output/deployment/compileContracts.js

COPY source/ /app/source/
RUN npx tsc

ENTRYPOINT [ "npx", "mocha", "output/tests-integration/**/*.js", "--no-timeouts", "--require", "source-map-support/register" ]
