def tests():
	self.testCashBal()
	self.testSendCash()
	self.testSendRep()
	self.testMakeBranch()
	self.testMakeEvent()
	self.testMakeMarket()
	self.testBuyShares()
	self.testSellShares()
	self.testVote()
	self.testQuoremChecker()
	self.testRedeem()
	self.testCloseMarket()
	return(array of these results)