#!/bin/bash

evm=$(serpent compile $1)
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_transact","params":[{"data": "0x'$evm'", "gas": 400000}],"id":1}' http://localhost:8080
serpent mk_full_signature $1
