FROM node:8.7.0

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY ./deploy-start.sh /app/deploy-start.sh
COPY ./transform-output.sh /app/transform-output.sh

WORKDIR /app
RUN npm install
COPY tsconfig.json /app/tsconfig.json
COPY typings/ /app/typings/
COPY source/ /app/source/

RUN npx tsc
RUN node ./output/deployment/compileContracts.js

ENTRYPOINT [ "bash", "./deploy-start.sh" ]
